//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cars()
        {
            this.Customers = new HashSet<Customers>();
        }
    
        public int id_Car { get; set; }
        public string Brand { get; set; }
        public Nullable<int> id_Manufacturer { get; set; }
        public int Type_id { get; set; }
        public Nullable<System.DateTime> data_Manufacture { get; set; }
        public string Color { get; set; }
        public string Number_body { get; set; }
        public string Characteristics { get; set; }
        public Nullable<int> Agreement_id_1 { get; set; }
        public Nullable<int> Agreement_id_2 { get; set; }
        public Nullable<int> Agreement_id_3 { get; set; }
        public string Price { get; set; }
        public Nullable<int> Staff_Id { get; set; }
    
        public virtual Manufactures Manufactures { get; set; }
        public virtual Staff Staff { get; set; }
        public virtual Supplementary_agreement Supplementary_agreement { get; set; }
        public virtual Supplementary_agreement Supplementary_agreement1 { get; set; }
        public virtual Supplementary_agreement Supplementary_agreement2 { get; set; }
        public virtual Type_body Type_body { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customers> Customers { get; set; }
    }
}
