//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cars.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customers
    {
        public string FIO { get; set; }
        public string Addres { get; set; }
        public string Pasport_data { get; set; }
        public Nullable<int> Car_id { get; set; }
        public string Data_order { get; set; }
        public string Date_sale { get; set; }
        public string Completion_mark { get; set; }
        public string Prepayment_percentage { get; set; }
        public Nullable<int> Staff_id { get; set; }
        public int id { get; set; }
    
        public virtual Cars Cars { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
